dataset: cifar100
model_name: tiny-resnet
epochs: 200
num_client: 10
client_epochs: 5
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: data/param_clip_models/ab66755a-a9d2-441e-abe1-8e7e13a8bb15
task_type: method1-r1
size: [32, 32]