dataset: cifar100
model_name: convnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 512
param_clip_ratio: 0.1
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: data/param_clip_models/568eca99-85b1-4d20-9188-af325d2a5cf3
task_type: method1-r1
size: [32, 32]