dataset: cifar10
model_name: tiny-resnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: noise
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.1
shapley_switch: none
num_classes: 10
checkpoint: data/param_clip_models/5d044bf6-f8ec-42a5-8294-b3ac3309144e
task_type: method1-r1
size: [32, 32]