dataset: stl10
model_name: bigresnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 114514
mode: noise
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
shapley_switch: none
num_classes: 10
checkpoint: data/param_clip_models/71c389e5-e281-4b1d-b238-dfbd79ebf4a6
task_type: method1-r1
size: [128, 128]