dataset: cifar100
model_name: tiny-resnet
epochs: 200
num_client: 10
client_epochs: 5
lr: 0.01
seed: 7517
mode: mask10
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.2
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: data/param_clip_models/60d154ed-0e28-4459-9ad2-9dcf99b2531d
task_type: method1-r2
size: [32, 32]