dataset: cifar100
model_name: tiny-resnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.2
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: /home/hao/data/CoAst_data/cs-cloud/data/param_clip_models/f4539998-6ead-43a2-b1a1-3bf3912b4ba2
task_type: method1-r2
size: [32, 32]
