dataset: cifar100
model_name: convnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 512
param_clip_ratio: 0.2
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: /home/hao/data/CoAst_data/cs-cloud/data/param_clip_models/ddb821cc-3e7a-4d58-a7e8-2bbf8449f8f6
task_type: method1-r2
size: [32, 32]
