dataset: cifar10
model_name: tiny-resnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: mask
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.2
step_size: 0.1
shapley_switch: none
num_classes: 10
checkpoint: data/param_clip_models/55a1e0b3-c8d5-41a2-9da4-b62d6c2c2fa6
task_type: method1-r2
size: [32, 32]