dataset: cifar100
model_name: convnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: mask
score_mode: spearman
batch_size: 512
param_clip_ratio: 0.2
step_size: 0.1
shapley_switch: none
num_classes: 100
checkpoint: /home/hao/data/CoAst_data/cs-cloud/data/param_clip_models/f4f9785d-2cf2-4967-bbd4-c04fd42ea820
task_type: method1-r2
size: [32, 32]
