dataset: stl10
model_name: bigresnet
epochs: 200
num_client: 5
client_epochs: 10
lr: 0.01
seed: 114514
mode: flip
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.2
step_size: 0.01
shapley_switch: none
num_classes: 10
checkpoint: 
task_type: method3-r2
size: [128, 128]