dataset: cifar100
model_name: tiny-resnet
epochs: 100
num_client: 10
client_epochs: 5
lr: 0.01
seed: 7517
mode: mask10
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
shapley_switch: none