dataset: tiny-imagenet
model_name: resnet18-nopre
epochs: 100
num_client: 5
client_epochs: 5
lr: 0.01
seed: 114514
mode: clean
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
shapley_switch: none