dataset: cifar100
model_name: tiny-resnet
epochs: 100
num_client: 10
client_epochs: 10
lr: 0.005
seed: 7517
mode: mask
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 100
checkpoint: data/baseline_models/687c4b1d-96be-49fd-a1a1-90833d8d083e
task_type: baseline
size: [32, 32]