dataset: cifar100
model_name: tiny-resnet
epochs: 100
num_client: 10
client_epochs: 10
lr: 0.005
seed: 7517
mode: noise
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 100
checkpoint: data/baseline_models/45d76000-d0e3-4e3a-ae1a-fc4e5ce03f78
task_type: baseline
size: [32, 32]