dataset: cifar10
model_name: tiny-resnet
epochs: 100
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 10
checkpoint: data/baseline_models/064f40f5-ab1f-4c7f-a72b-433964c4e7eb
task_type: baseline
size: [32, 32]

