dataset: cifar100
model_name: convnet
epochs: 50
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: blur
score_mode: spearman
batch_size: 512
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 100
checkpoint: data/baseline_models/69d290f3-b00d-4647-af05-c6010b931b35
task_type: baseline
size: [32, 32]