dataset: cifar100
model_name: convnet
epochs: 50
num_client: 5
client_epochs: 10
lr: 0.01
seed: 7517
mode: mask
score_mode: spearman
batch_size: 512
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 100
checkpoint: data/baseline_models/6c76890d-4918-409e-bd66-ebf426aa2e1f
task_type: baseline
size: [32, 32]