dataset: cifar100
model_name: tiny-resnet
epochs: 100
num_client: 5
client_epochs: 10
lr: 0.005
seed: 7517
mode: count
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 100
checkpoint: data/baseline_models/6ec6b4de-7969-4cf8-9098-af0b2d7c96b3
task_type: baseline
size: [32, 32]