dataset: stl10
model_name: bigresnet
epochs: 100
num_client: 5
client_epochs: 10
lr: 0.01
seed: 114514
mode: noise
score_mode: spearman
batch_size: 1024
param_clip_ratio: 0.1
step_size: 0.01
num_classes: 10
checkpoint: data/baseline_models/e5685e88-6014-498f-b6b3-5ebda547eb27
task_type: baseline
size: [128, 128]